FROM mariadb:11

# Como ya estamos en ./infra/db-usuarios, buscamos los archivos directamente ahí
COPY script_DDL_usuario.sql /docker-entrypoint-initdb.d/01_schema.sql
COPY script_DML_usuario.sql /docker-entrypoint-initdb.d/02_seed.sql

VOLUME /var/lib/mysql