spring.application.name=api-gateway
server.port=8080

# ✅ Routing hacia ms-inventario
spring.cloud.gateway.routes[0].id=ms-inventario
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/productos/**

# ✅ Routing hacia ms-usuarios
spring.cloud.gateway.routes[1].id=ms-usuarios
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/usuarios/**